language: java
jdk: oraclejdk8
env.global:
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092
  - DOCKER_HOST=localhost
script:
  - gradle build
  - gradle dependencyUpdates -Drevision=release -DoutputFormatter=json,plain -DoutputDir=./build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache.directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
