spring:
  data:
    mongodb:
      port: 0
    rest:
      base-path: /api
  application:
    name: resource-server
  mongodb:
    embedded:
      storage:
        database-dir: db
      features:
server:
  port: 9000
management:
  context-path: /admin
