spring:
  application:
    name: authorization-server
  mustache:
    cache: false
    suffix: .hbs
server:
  port: 9999
  context-path: /uaa
security:
  user:
    name: usr
    password: pwd
management:
  context-path: /admin
