spring:
  application:
    name: authorization-server
  data:
    mongodb:
      port: 0
server:
  port: 9999
  context-path: /uaa
security:
  user:
    name: usr
    password: pwd
management:
  context-path: /admin
logging.level:
  org.springframework.security: DEBUG
